### ISSUE TITLE
`meteor run`, `meteor mongo` crash and burn (0.7.1.2/WinXP)

### ISSUE THREAD

**Issue by FaultyRAM** [sdarnell/meteor-win#35]
Executing `meteor run` for a newly-created project with release 0.7.1.2 on Windows XP results in the stack trace below, and likewise for `meteor mongo`:

```
J:\msys\home\faultyram\meteor\leaderboard>meteor
[[[[[ J:\msys\home\faultyram\meteor\foobar ]]]]]

=> Started proxy.
=> Starting MongoDB... -[G
C:\Documents and Settings\faultyram\Application Data\.meteor\tools\47782522f9\lib\node_modules\fibers\future.js:206
            throw(ex);
                  ^
Error: Couldn't run tasklist: {"killed":false,"code":-1073741515,"signal":null}
    at Object.Future.wait (C:\Documents and Settings\faultyram\Application Data\.meteor\tools\47782522f9\lib\node_modules\fibers\future.js:326:15)
    at findMongoPids (C:\Documents and Settings\faultyram\Application Data\.meteor\tools\47782522f9\tools\run-mongo.js:142:16)
    at findMongoAndKillItDead (C:\Documents and Settings\faultyram\Application Data\.meteor\tools\47782522f9\tools\run-mongo.js:172:14)
    at C:\Documents and Settings\faultyram\Application Data\.meteor\tools\47782522f9\tools\run-mongo.js:265:5
    - - - - -
    at C:\Documents and Settings\faultyram\Application Data\.meteor\tools\47782522f9\tools\run-mongo.js:97:24
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

This occurs with a fresh install, with and without a separate Node.js installation. According to a quick Google search, the error code -1073741515 is defined in ntstatus.h as `STATUS_DLL_NOT_FOUND`, so there may be a dependency issue somewhere.

**Comment by sdarnell** [comment]
Can you run tasklist from the command line? Could it be that it is not on your PATH?

**Comment by FaultyRAM** [comment]
Whoops, you're right. My PATH was badly configured. Recently a broken app managed to wipe it out, and I had to rebuild it from scratch...except I typo'd the path to `%SystemRoot%\system32\wbem`. Thus tasklist.exe couldn't find framedyn.dll, thus it couldn't run, thus Meteor crashed. That's fixed now, and Meteor runs fine, so I'll close this bug. Thanks for your assistance, and sorry to waste time like this!

**Comment by sdarnell** [comment]
@FaultyRAM Glad I was able to help and that sorted it.
