### ISSUE TITLE
Antivirus can get in the way of LaunchMeteor

### ISSUE THREAD

**Issue by sdarnell** [sdarnell/meteor-win#43]
When running LaunchMeteor.exe it can be thwarted by antivirus programs still scanning:

```
...
Extracted 6770 files (114.2 MB)
Deleting directory: C:\Users\stephendar\AppData\Local\.meteor~
Unexpected exception: System.IO.IOException: Access to the path 'C:\Users\stephendar\AppData\Local\.meteor~' is denied.
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at LaunchMeteor.Program.BootstrapWarehouse(String warehouse)
   at LaunchMeteor.Program.Main(String[] args)
```

By pausing the process (selecting text in the window) I could make it succeed, which strongly suggests antivirus scanning.

So, LaunchMeteor should pause a bit and retry.

**Comment by cguettinger** [comment]
I had the same issue when installing the last LaunchMeteor09.exe (just few minutes ago). Situation was that there existed no .meteor folder before executing because I deleted it manually. afterwards I installed it with administrator privileges and it succeeded. Might be coincedence though.
