### ISSUE TITLE
Newly created app does not start for 0.9.0.1

### ISSUE THREAD

**Issue by cguettinger** [sdarnell/meteor-win#60]
Just created a new app. Did not make any changes.
System: Windows 7
Error is:

D:\meteor_windows\newapp>meteor
[[[[[ D:\meteor_windows\newapp ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Starting your app...
C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:173
                                                throw(ex);
                                                      ^
Error: EPERM, operation not permitted 'D:\meteor_windows\newapp.meteor\local.build40727.build\programs\ctl'
    at Object.fs.renameSync (fs.js:548:18)
    at C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\files.js:664:8
    at Object.files.retryOnEperm (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\files.js:625:7)
    at Object.files.renameDirAlmostAtomically (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\files.js:663:9)
    at _.extend.complete (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\builder.js:516:11)
    at writeTargetToPath (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\bundler.js:1515:11)
    at C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\bundler.js:1614:26
    at Function._.each._.forEach (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at writeSiteArchive (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\bundler.js:1613:7)
    at C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\bundler.js:1999:20
    at C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\buildmessage.js:186:11
    at _.extend.withValue (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\fiber-helpers.js:112:14)
    at C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\buildmessage.js:183:27
    at _.extend.withValue (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\fiber-helpers.js:112:14)
    at C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\buildmessage.js:181:16
    at _.extend.withValue (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\fiber-helpers.js:112:14)
    at Object.capture (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\buildmessage.js:172:21)
    at Object.exports.bundle (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\bundler.js:1714:31)
    at bundleApp (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\run-app.js:469:28)
    at _.extend._runOnce (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\run-app.js:487:24)
    at _.extend._fiber (C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\run-app.js:670:28)
    at C:\Users\cgr\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\run-app.js:360:12

**Comment by sdarnell** [comment]
@cguettinger  It appears that either you have a file open in the build dir (unlikely), or anti-virus scanner is scanning it (and all of the new data that just appeared), or you have an editor that is scanning that directory.  If it is the latter, you may be able to configure it to not scan the .meteor directory.

The rename code tries 5 times, with a 100ms between each attempt. After this it gives up (as above).
500ms isn't that long, and increasing it makes sense - as failure is quite serious.

If it is the 500ms limit being a bit too short, I would expect that it would occasionally succeed. Does it?

**Comment by cguettinger** [comment]
I reinstalled with the latest LaunchMeteor09.exe after deleting the .meteor folder. Now I can create a new app and it starts without any issues :-)
