### ISSUE TITLE
Exception after change file

### ISSUE THREAD

**Issue by lxblink** [sdarnell/meteor-win#64]
After issue with buildinfo,json have new one:

```
D:\work\meteor_proj\napp>meteor
[[[[[ D:\work\meteor_proj\napp ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
```

All OK, for now.
Next I change css, save file, and I see in the console (after some delay):

```
C:\Users\X\AppData\Local\.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:175
                                                throw(ex);
                                                      ^
Error: Unknown signal: SIGUSR2
    at process.kill (node.js:728:17)
    at _.extend._runOnce (C:\Users\X\AppData\Local\.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\run-app.js:617:17)
    at _.extend._fiber (C:\Users\X\AppData\Local\.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\run-app.js:670:28)
    at C:\Users\X\AppData\Local\.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\run-app.js:360:12
```

System info:
Win 8.1, x64
was used clean installation of LaunchMeteor09.exe

**Comment by sdarnell** [comment]
I have a work-around (fix is too strong a word for it). The way client changes get detected has changed (optimised) but uses a mechanism that isn't available on Windows.
See https://github.com/sdarnell/meteor/commit/a85ad0699b2bbd9bfe0bf4c9992a2ee741481421

Until I release a new update (which should be soon), find run_app.js:
`C:\Users\X\AppData\Local\.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\run-app.js`

And change the line that sends the SIGHUP2, to remove the second parameter to become: 

```
process.kill(appProcess.proc.pid);
```

I'm leaving this issue open as I'd like to see if there is a cleaner way of doing the client restart.
